version: '3.9'

services:
  postgres:
    container_name: pw_pg
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
